/**
 * Static mock data for the Workspace page.
 * Phase 2 replaces these with Convex queries.
 */

export type FileNode =
  | { type: "folder"; name: string; open?: boolean; children: ReadonlyArray<FileNode> }
  | { type: "file"; name: string; active?: boolean };

export const FILE_TREE: ReadonlyArray<FileNode> = [
  {
    type: "folder",
    name: "src",
    open: true,
    children: [
      {
        type: "folder",
        name: "components",
        open: true,
        children: [
          { type: "file", name: "TodoList.tsx", active: true },
          { type: "file", name: "TodoItem.tsx" },
          { type: "file", name: "AddTodo.tsx" },
        ],
      },
      { type: "file", name: "App.tsx" },
      { type: "file", name: "main.tsx" },
      { type: "file", name: "index.css" },
    ],
  },
  {
    type: "folder",
    name: "public",
    children: [{ type: "file", name: "favicon.svg" }],
  },
  { type: "file", name: "package.json" },
  { type: "file", name: "tsconfig.json" },
  { type: "file", name: "vite.config.ts" },
  { type: "file", name: "README.md" },
];

export type TokenKind =
  | "kw"
  | "str"
  | "fn"
  | "com"
  | "num"
  | "prop"
  | "tag"
  | "attr"
  | "pun"
  | "jsx";

export type CodeLine = { tokens: ReadonlyArray<readonly [TokenKind, string]> };

export const CODE_LINES: ReadonlyArray<CodeLine> = [
  { tokens: [["com", "// TodoList.tsx — generated by Nexus"]] },
  {
    tokens: [
      ["kw", "import"],
      ["pun", " { "],
      ["fn", "useState"],
      ["pun", ", "],
      ["fn", "useEffect"],
      ["pun", " } "],
      ["kw", "from"],
      ["pun", " "],
      ["str", "'react'"],
    ],
  },
  {
    tokens: [
      ["kw", "import"],
      ["pun", " "],
      ["fn", "TodoItem"],
      ["pun", " "],
      ["kw", "from"],
      ["pun", " "],
      ["str", "'./TodoItem'"],
    ],
  },
  {
    tokens: [
      ["kw", "import"],
      ["pun", " "],
      ["fn", "AddTodo"],
      ["pun", " "],
      ["kw", "from"],
      ["pun", " "],
      ["str", "'./AddTodo'"],
    ],
  },
  { tokens: [] },
  {
    tokens: [
      ["kw", "type"],
      ["pun", " "],
      ["fn", "Todo"],
      ["pun", " = { "],
      ["prop", "id"],
      ["pun", ": "],
      ["kw", "string"],
      ["pun", "; "],
      ["prop", "text"],
      ["pun", ": "],
      ["kw", "string"],
      ["pun", "; "],
      ["prop", "done"],
      ["pun", ": "],
      ["kw", "boolean"],
      ["pun", " }"],
    ],
  },
  { tokens: [] },
  {
    tokens: [
      ["kw", "export default function"],
      ["pun", " "],
      ["fn", "TodoList"],
      ["pun", "() {"],
    ],
  },
  {
    tokens: [
      ["pun", "  "],
      ["kw", "const"],
      ["pun", " ["],
      ["prop", "todos"],
      ["pun", ", "],
      ["fn", "setTodos"],
      ["pun", "] = "],
      ["fn", "useState"],
      ["pun", "<"],
      ["fn", "Todo"],
      ["pun", "[]>([])"],
    ],
  },
  { tokens: [] },
  {
    tokens: [
      ["pun", "  "],
      ["fn", "useEffect"],
      ["pun", "(() => {"],
    ],
  },
  {
    tokens: [
      ["pun", "    "],
      ["fn", "fetch"],
      ["pun", "("],
      ["str", "'/api/todos'"],
      ["pun", ")"],
    ],
  },
  {
    tokens: [
      ["pun", "      ."],
      ["fn", "then"],
      ["pun", "(r => r."],
      ["fn", "json"],
      ["pun", "())"],
    ],
  },
  {
    tokens: [
      ["pun", "      ."],
      ["fn", "then"],
      ["pun", "("],
      ["fn", "setTodos"],
      ["pun", ")"],
    ],
  },
  { tokens: [["pun", "  }, [])"]] },
  { tokens: [] },
  {
    tokens: [
      ["pun", "  "],
      ["kw", "return"],
      ["pun", " ("],
    ],
  },
  {
    tokens: [
      ["pun", "    <"],
      ["tag", "section"],
      ["pun", " "],
      ["attr", "className"],
      ["pun", "="],
      ["str", '"todo-app"'],
      ["pun", ">"],
    ],
  },
  {
    tokens: [
      ["pun", "      <"],
      ["tag", "h1"],
      ["pun", ">"],
      ["jsx", "Today"],
      ["pun", "</"],
      ["tag", "h1"],
      ["pun", ">"],
    ],
  },
  {
    tokens: [
      ["pun", "      <"],
      ["tag", "AddTodo"],
      ["pun", " "],
      ["attr", "onAdd"],
      ["pun", "={t => "],
      ["fn", "setTodos"],
      ["pun", "(["],
      ["pun", "..."],
      ["prop", "todos"],
      ["pun", ", t])} />"],
    ],
  },
  {
    tokens: [
      ["pun", "      {"],
      ["prop", "todos"],
      ["pun", "."],
      ["fn", "map"],
      ["pun", "(t => <"],
      ["tag", "TodoItem"],
      ["pun", " "],
      ["attr", "key"],
      ["pun", "={t."],
      ["prop", "id"],
      ["pun", "} "],
      ["attr", "todo"],
      ["pun", "={t} />)}"],
    ],
  },
  {
    tokens: [
      ["pun", "    </"],
      ["tag", "section"],
      ["pun", ">"],
    ],
  },
  { tokens: [["pun", "  )"]] },
  { tokens: [["pun", "}"]] },
];

export type TermLine = {
  kind: "cmd" | "out" | "err" | "meta";
  text: string;
};

export const TERM_LINES: ReadonlyArray<TermLine> = [
  { kind: "cmd", text: "pnpm install" },
  { kind: "meta", text: "Resolving dependencies…" },
  { kind: "meta", text: "Packages: +247" },
  { kind: "out", text: "Done in 3.2s" },
  { kind: "cmd", text: "pnpm dev" },
  { kind: "meta", text: "VITE v5.2.1  ready in 412 ms" },
  { kind: "out", text: "➜  Local:   http://localhost:5173/" },
  { kind: "out", text: "➜  Preview: https://preview-7f3a-ax21.daytona.dev" },
  { kind: "meta", text: "[hmr] update /src/components/TodoList.tsx" },
  { kind: "meta", text: "[hmr] update /src/components/AddTodo.tsx" },
  { kind: "out", text: "✓ Build complete · Preview ready" },
];
