/* Workspace — Nexus main product UI */

const FILE_TREE = [
  { type: 'folder', name: 'src', open: true, children: [
    { type: 'folder', name: 'components', open: true, children: [
      { type: 'file', name: 'TodoList.tsx', active: true },
      { type: 'file', name: 'TodoItem.tsx' },
      { type: 'file', name: 'AddTodo.tsx' },
    ]},
    { type: 'file', name: 'App.tsx' },
    { type: 'file', name: 'main.tsx' },
    { type: 'file', name: 'index.css' },
  ]},
  { type: 'folder', name: 'public', children: [
    { type: 'file', name: 'favicon.svg' },
  ]},
  { type: 'file', name: 'package.json' },
  { type: 'file', name: 'tsconfig.json' },
  { type: 'file', name: 'vite.config.ts' },
  { type: 'file', name: 'README.md' },
];

const FileTreeNode = ({ node, depth = 0 }) => {
  const [open, setOpen] = React.useState(node.open || false);
  if (node.type === 'folder') {
    return (
      <div>
        <div onClick={() => setOpen(o => !o)} style={{
          display: 'flex', alignItems: 'center', gap: 6,
          padding: `4px 8px 4px ${8 + depth * 12}px`,
          fontSize: 12.5, color: 'var(--text-secondary)',
          cursor: 'pointer', userSelect: 'none',
        }}
        onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.03)'}
        onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
          <IconChevron size={11} style={{
            transform: open ? 'rotate(90deg)' : 'rotate(0)',
            transition: 'transform 150ms', color: 'var(--text-tertiary)',
          }}/>
          <IconFolder size={13} style={{ color: 'var(--text-tertiary)'}}/>
          <span>{node.name}</span>
        </div>
        {open && node.children?.map((c, i) => (
          <FileTreeNode key={i} node={c} depth={depth + 1}/>
        ))}
      </div>
    );
  }
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 6,
      padding: `4px 8px 4px ${24 + depth * 12}px`,
      fontSize: 12.5,
      color: node.active ? 'var(--text-primary)' : 'var(--text-secondary)',
      background: node.active ? 'rgba(0,229,255,0.07)' : 'transparent',
      borderLeft: node.active ? '2px solid var(--accent-cyan)' : '2px solid transparent',
      marginLeft: node.active ? -2 : 0,
      cursor: 'pointer',
    }}
    onMouseEnter={e => { if (!node.active) e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; }}
    onMouseLeave={e => { if (!node.active) e.currentTarget.style.background = 'transparent'; }}>
      <IconFile size={12} style={{ color: 'var(--text-tertiary)'}}/>
      <span>{node.name}</span>
    </div>
  );
};

/* Streamed code lines for the editor */
const CODE_LINES = [
  { tokens: [['com', '// TodoList.tsx — generated by Nexus']] },
  { tokens: [['kw', 'import'], ['pun', ' { '], ['fn', 'useState'], ['pun', ', '], ['fn', 'useEffect'], ['pun', ' } '], ['kw', 'from'], ['pun', ' '], ['str', "'react'"]] },
  { tokens: [['kw', 'import'], ['pun', ' '], ['fn', 'TodoItem'], ['pun', ' '], ['kw', 'from'], ['pun', ' '], ['str', "'./TodoItem'"]] },
  { tokens: [['kw', 'import'], ['pun', ' '], ['fn', 'AddTodo'], ['pun', ' '], ['kw', 'from'], ['pun', ' '], ['str', "'./AddTodo'"]] },
  { tokens: [] },
  { tokens: [['kw', 'type'], ['pun', ' '], ['fn', 'Todo'], ['pun', ' = { '], ['prop', 'id'], ['pun', ': '], ['kw', 'string'], ['pun', '; '], ['prop', 'text'], ['pun', ': '], ['kw', 'string'], ['pun', '; '], ['prop', 'done'], ['pun', ': '], ['kw', 'boolean'], ['pun', ' }']] },
  { tokens: [] },
  { tokens: [['kw', 'export default function'], ['pun', ' '], ['fn', 'TodoList'], ['pun', '() {']] },
  { tokens: [['pun', '  '], ['kw', 'const'], ['pun', ' ['], ['prop', 'todos'], ['pun', ', '], ['fn', 'setTodos'], ['pun', '] = '], ['fn', 'useState'], ['pun', '<'], ['fn', 'Todo'], ['pun', '[]>([])']] },
  { tokens: [] },
  { tokens: [['pun', '  '], ['fn', 'useEffect'], ['pun', '(() => {']] },
  { tokens: [['pun', '    '], ['fn', 'fetch'], ['pun', '('], ['str', "'/api/todos'"], ['pun', ')']] },
  { tokens: [['pun', '      .'], ['fn', 'then'], ['pun', '(r => r.'], ['fn', 'json'], ['pun', '())']] },
  { tokens: [['pun', '      .'], ['fn', 'then'], ['pun', '('], ['fn', 'setTodos'], ['pun', ')']] },
  { tokens: [['pun', '  }, [])']] },
  { tokens: [] },
  { tokens: [['pun', '  '], ['kw', 'return'], ['pun', ' (']] },
  { tokens: [['pun', '    <'], ['tag', 'section'], ['pun', ' '], ['attr', 'className'], ['pun', '='], ['str', '"todo-app"'], ['pun', '>']] },
  { tokens: [['pun', '      <'], ['tag', 'h1'], ['pun', '>'], ['jsx', 'Today'], ['pun', '</'], ['tag', 'h1'], ['pun', '>']] },
  { tokens: [['pun', '      <'], ['tag', 'AddTodo'], ['pun', ' '], ['attr', 'onAdd'], ['pun', '={t => '], ['fn', 'setTodos'], ['pun', '(['], ['pun', '...'], ['prop', 'todos'], ['pun', ', t])} />']] },
  { tokens: [['pun', '      {'], ['prop', 'todos'], ['pun', '.'], ['fn', 'map'], ['pun', '(t => <'], ['tag', 'TodoItem'], ['pun', ' '], ['attr', 'key'], ['pun', '={t.'], ['prop', 'id'], ['pun', '} '], ['attr', 'todo'], ['pun', '={t} />)}']] },
  { tokens: [['pun', '    </'], ['tag', 'section'], ['pun', '>']] },
  { tokens: [['pun', '  )']] },
  { tokens: [['pun', '}']] },
];

const renderTokens = (tokens) => tokens.map(([k, t], i) => (
  <span key={i} className={`tok-${k}`}>{t}</span>
));

const CodeEditor = ({ streamProgress, isStreaming }) => {
  const totalLines = CODE_LINES.length;
  const fullLines = Math.floor(streamProgress);
  const partial = streamProgress - fullLines;

  const scrollerRef = React.useRef(null);
  React.useEffect(() => {
    if (scrollerRef.current && isStreaming) {
      scrollerRef.current.scrollTop = scrollerRef.current.scrollHeight;
    }
  }, [streamProgress, isStreaming]);

  return (
    <div style={{ display: 'flex', height: '100%', minHeight: 0 }}>
      {/* file tree */}
      <div style={{
        width: 220, borderRight: '1px solid var(--border-subtle)',
        background: 'var(--bg-surface)', padding: '14px 0',
        overflowY: 'auto', flexShrink: 0,
      }}>
        <div style={{
          padding: '0 14px 12px', fontSize: 11, letterSpacing: '0.14em',
          textTransform: 'uppercase', color: 'var(--text-tertiary)',
          display: 'flex', alignItems: 'center', gap: 8, fontWeight: 500,
        }}>
          <span style={{ flex: 1 }}>Explorer</span>
          <span className="mono" style={{
            color: 'var(--accent-cyan)', fontSize: 10,
            background: 'rgba(0,229,255,0.08)',
            padding: '2px 6px', borderRadius: 4,
            letterSpacing: '0.04em',
          }}>{isStreaming ? 'WRITING' : 'IDLE'}</span>
        </div>
        {FILE_TREE.map((n, i) => <FileTreeNode key={i} node={n}/>)}
      </div>

      {/* editor */}
      <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' }}>
        {/* breadcrumb */}
        <div style={{
          height: 30, display: 'flex', alignItems: 'center',
          padding: '0 18px', gap: 6,
          borderBottom: '1px solid var(--border-subtle)',
          fontSize: 12, color: 'var(--text-tertiary)',
          fontFamily: 'JetBrains Mono', background: 'rgba(0,0,0,0.2)',
        }}>
          <IconFolder size={11}/>
          <span>src</span>
          <IconChevron size={10}/>
          <span>components</span>
          <IconChevron size={10}/>
          <span style={{ color: 'var(--text-primary)' }}>TodoList.tsx</span>
        </div>
        <div ref={scrollerRef} style={{
          flex: 1, overflowY: 'auto', padding: '10px 0',
          background: 'var(--bg-canvas)', minHeight: 0,
        }}>
          {CODE_LINES.slice(0, fullLines).map((line, i) => (
            <div key={i} className="code-line">
              <span className="code-gutter">{i + 1}</span>
              <span className="code-content">{renderTokens(line.tokens)}</span>
            </div>
          ))}
          {fullLines < totalLines && (() => {
            const cur = CODE_LINES[fullLines];
            // approximate visible chars
            const fullText = cur.tokens.map(([_, t]) => t).join('');
            const visibleLen = Math.floor(fullText.length * partial);
            let acc = 0;
            const visible = [];
            for (const [k, t] of cur.tokens) {
              if (acc >= visibleLen) break;
              const remaining = visibleLen - acc;
              if (t.length <= remaining) {
                visible.push([k, t]);
                acc += t.length;
              } else {
                visible.push([k, t.slice(0, remaining)]);
                acc = visibleLen;
              }
            }
            return (
              <div className="code-line">
                <span className="code-gutter">{fullLines + 1}</span>
                <span className="code-content">
                  {renderTokens(visible)}
                  {isStreaming && <span className="cursor-blink"/>}
                </span>
              </div>
            );
          })()}
          {fullLines >= totalLines && isStreaming && (
            <div className="code-line">
              <span className="code-gutter">{totalLines + 1}</span>
              <span className="code-content"><span className="cursor-blink"/></span>
            </div>
          )}
          <div style={{ height: 80 }}/>
        </div>
        {/* status bar */}
        <div style={{
          height: 26, display: 'flex', alignItems: 'center',
          padding: '0 14px', gap: 18,
          borderTop: '1px solid var(--border-subtle)',
          fontSize: 11, color: 'var(--text-tertiary)',
          fontFamily: 'JetBrains Mono',
          background: 'rgba(0,0,0,0.3)',
        }}>
          <span style={{ color: 'var(--accent-cyan)'}}>● TypeScript React</span>
          <span>UTF-8</span>
          <span>LF</span>
          <div style={{ flex: 1 }}/>
          <span>Ln {fullLines + 1}, Col 1</span>
          <span>{isStreaming ? 'Streaming…' : 'Saved'}</span>
        </div>
      </div>
    </div>
  );
};

/* Live preview tab — fake browser shell */
const LivePreview = () => {
  const [copied, setCopied] = React.useState(false);
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <div style={{
        height: 40, display: 'flex', alignItems: 'center', gap: 10,
        padding: '0 14px', borderBottom: '1px solid var(--border-subtle)',
        background: 'rgba(0,0,0,0.3)',
      }}>
        <div style={{ display: 'flex', gap: 6 }}>
          <span style={{ width: 10, height: 10, borderRadius: 999, background: '#27272A'}}/>
          <span style={{ width: 10, height: 10, borderRadius: 999, background: '#27272A'}}/>
          <span style={{ width: 10, height: 10, borderRadius: 999, background: '#27272A'}}/>
        </div>
        <div className="mono" style={{
          flex: 1, height: 26, borderRadius: 999,
          background: 'var(--bg-canvas)',
          border: '1px solid var(--border-subtle)',
          display: 'flex', alignItems: 'center', gap: 8,
          padding: '0 12px', fontSize: 11.5,
          color: 'var(--text-secondary)',
        }}>
          <IconLock size={11} style={{ color: 'var(--text-success)' }}/>
          <span style={{ color: 'var(--text-tertiary)' }}>https://</span>
          <span>preview-7f3a-ax21.daytona.dev</span>
          <div style={{ flex: 1 }}/>
          <span style={{
            fontSize: 10, padding: '1px 7px', borderRadius: 999,
            background: 'rgba(0,255,133,0.12)', color: '#00FF85',
            border: '1px solid rgba(0,255,133,0.3)',
            letterSpacing: '0.08em', textTransform: 'uppercase',
          }}>live</span>
        </div>
        <button className="btn-icon" title="Copy URL" onClick={() => {
          setCopied(true); setTimeout(() => setCopied(false), 1500);
        }}>
          {copied ? <span style={{ fontSize: 11, color: 'var(--accent-cyan)' }}>✓</span> : <IconCopy size={13}/>}
        </button>
      </div>

      {/* fake app preview */}
      <div style={{
        flex: 1, padding: 32, display: 'flex',
        alignItems: 'flex-start', justifyContent: 'center',
        background: '#fafafa', overflow: 'auto',
      }}>
        <div style={{
          width: '100%', maxWidth: 460, padding: 36,
          borderRadius: 18, background: '#fff',
          boxShadow: '0 12px 40px -12px rgba(0,0,0,0.18), 0 1px 0 rgba(0,0,0,0.04)',
          fontFamily: 'Inter',
          color: '#0A0A0A',
        }}>
          <div style={{ fontSize: 13, color: '#71717A', letterSpacing: '0.18em',
            textTransform: 'uppercase', fontWeight: 500, marginBottom: 6 }}>
            Friday, May 9
          </div>
          <h1 style={{ fontSize: 36, fontWeight: 700, margin: '0 0 24px',
            letterSpacing: '-0.02em' }}>Today</h1>
          <div style={{
            display: 'flex', gap: 8, marginBottom: 20,
            padding: '12px 14px', borderRadius: 12,
            border: '1px solid #E4E4E7',
          }}>
            <div style={{
              width: 18, height: 18, borderRadius: 6,
              border: '1.5px solid #D4D4D8'
            }}/>
            <input placeholder="Add a todo…" style={{
              flex: 1, border: 'none', outline: 'none', background: 'transparent',
              fontSize: 14, color: '#0A0A0A',
            }}/>
          </div>
          {[
            { text: 'Ship Nexus landing page', done: true },
            { text: 'Review Daytona sandbox config', done: false },
            { text: 'Wire up live preview iframe', done: false },
            { text: 'Record demo video', done: false },
          ].map((t, i) => (
            <div key={i} style={{
              display: 'flex', alignItems: 'center', gap: 12,
              padding: '10px 4px',
              borderBottom: i < 3 ? '1px solid #F4F4F5' : 'none',
            }}>
              <div style={{
                width: 18, height: 18, borderRadius: 6,
                background: t.done ? '#0A0A0A' : '#fff',
                border: '1.5px solid ' + (t.done ? '#0A0A0A' : '#D4D4D8'),
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                color: '#fff', fontSize: 11,
              }}>{t.done ? '✓' : ''}</div>
              <div style={{
                fontSize: 15,
                color: t.done ? '#A1A1AA' : '#0A0A0A',
                textDecoration: t.done ? 'line-through' : 'none',
              }}>{t.text}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

const InsightsTab = ({ termLines, isStreaming }) => {
  const termRef = React.useRef(null);
  React.useEffect(() => {
    if (termRef.current) termRef.current.scrollTop = termRef.current.scrollHeight;
  }, [termLines]);
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      {/* AI explanation top */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '24px 28px', minHeight: 0 }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          fontSize: 11, letterSpacing: '0.16em', textTransform: 'uppercase',
          color: 'var(--accent-purple)', marginBottom: 14, fontWeight: 500,
        }}>
          <span className="status-dot thinking"/>
          Nexus is thinking
        </div>
        <h3 style={{
          fontSize: 20, fontWeight: 600, margin: '0 0 14px',
          letterSpacing: '-0.01em',
        }}>I created a React Todo app with a typed API layer.</h3>
        <div style={{
          color: 'var(--text-secondary)', fontSize: 14.5,
          lineHeight: 1.65, maxWidth: 720,
        }}>
          <p style={{ marginTop: 0 }}>
            Here's what I just shipped:
          </p>
          <ul style={{ paddingLeft: 18, margin: '0 0 12px' }}>
            <li><span style={{ color: 'var(--text-primary)' }}>TodoList.tsx</span> &mdash; the main view, fetches from <span className="mono" style={{ color: 'var(--accent-cyan)' }}>/api/todos</span> on mount and keeps state in <span className="mono" style={{ color: 'var(--accent-cyan)' }}>useState</span>.</li>
            <li><span style={{ color: 'var(--text-primary)' }}>TodoItem.tsx</span> &mdash; presentational, supports inline edit and a strikethrough animation.</li>
            <li><span style={{ color: 'var(--text-primary)' }}>AddTodo.tsx</span> &mdash; controlled input with optimistic insert.</li>
          </ul>
          <p>
            I deployed it to your Daytona sandbox at <span className="mono" style={{ color: 'var(--accent-cyan)' }}>preview-7f3a-ax21.daytona.dev</span>.
            Want me to add a backend with persistence next? I'd recommend Convex.
          </p>
        </div>
      </div>

      {/* terminal */}
      <div style={{
        height: '40%', minHeight: 180,
        borderTop: '1px solid var(--border-subtle)',
        background: '#000',
        display: 'flex', flexDirection: 'column',
      }}>
        <div style={{
          height: 30, display: 'flex', alignItems: 'center', gap: 12,
          padding: '0 14px',
          borderBottom: '1px solid var(--border-subtle)',
          fontSize: 11, color: 'var(--text-tertiary)',
          letterSpacing: '0.12em', textTransform: 'uppercase',
        }}>
          <span style={{ color: 'var(--text-secondary)', fontWeight: 500 }}>Terminal</span>
          <span className="mono" style={{ textTransform: 'none', letterSpacing: 0,
            color: 'var(--text-tertiary)' }}>daytona@7f3a-ax21:~/app$</span>
          <div style={{ flex: 1 }}/>
          {isStreaming && <span style={{ color: 'var(--accent-cyan)' }}>● running</span>}
        </div>
        <div ref={termRef} style={{
          flex: 1, overflowY: 'auto', padding: '10px 0',
        }}>
          {termLines.map((line, i) => (
            <div key={i} className="term-line">
              {line.kind === 'cmd' && <span className="term-prompt">$</span>}
              <span className={
                line.kind === 'out' ? 'term-out' :
                line.kind === 'err' ? 'term-err' :
                line.kind === 'cmd' ? 'mono' :
                'term-meta'
              } style={ line.kind === 'cmd' ? { color: 'var(--text-primary)' } : {}}>
                {line.text}
              </span>
            </div>
          ))}
          {isStreaming && (
            <div className="term-line">
              <span className="term-prompt">$</span>
              <span className="cursor-blink" style={{ height: 14 }}/>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

/* ====== Main Workspace ====== */
const Workspace = ({ onNavProfile, onLeave, leftWidth, setLeftWidth }) => {
  const [activeTab, setActiveTab] = React.useState('preview');
  const [muted, setMuted] = React.useState(false);
  const [aiState, setAiState] = React.useState('speaking'); // listening | thinking | speaking
  const [streamProgress, setStreamProgress] = React.useState(0);
  const [termLines, setTermLines] = React.useState([
    { kind: 'cmd', text: 'pnpm install' },
    { kind: 'meta', text: 'Resolving dependencies…' },
    { kind: 'meta', text: 'Packages: +247' },
    { kind: 'out', text: 'Done in 3.2s' },
    { kind: 'cmd', text: 'pnpm dev' },
    { kind: 'meta', text: 'VITE v5.2.1  ready in 412 ms' },
    { kind: 'out', text: '➜  Local:   http://localhost:5173/' },
    { kind: 'out', text: '➜  Preview: https://preview-7f3a-ax21.daytona.dev' },
  ]);

  // cycle the AI states for life
  React.useEffect(() => {
    const cycle = ['speaking', 'speaking', 'thinking', 'listening'];
    let i = 0;
    const id = setInterval(() => {
      i = (i + 1) % cycle.length;
      setAiState(cycle[i]);
    }, 4200);
    return () => clearInterval(id);
  }, []);

  // stream the code
  React.useEffect(() => {
    const id = setInterval(() => {
      setStreamProgress(p => Math.min(p + 0.18, CODE_LINES.length));
    }, 90);
    return () => clearInterval(id);
  }, []);

  // append terminal lines as code progresses
  const isStreaming = streamProgress < CODE_LINES.length;
  React.useEffect(() => {
    if (streamProgress > 6 && termLines.length === 8) {
      setTermLines(t => [...t, { kind: 'meta', text: '[hmr] update /src/components/TodoList.tsx' }]);
    }
    if (streamProgress > 14 && termLines.length === 9) {
      setTermLines(t => [...t, { kind: 'meta', text: '[hmr] update /src/components/AddTodo.tsx' }]);
    }
    if (streamProgress >= CODE_LINES.length && termLines.length === 10) {
      setTermLines(t => [...t,
        { kind: 'out', text: '✓ Build complete · Preview ready' }
      ]);
    }
  }, [streamProgress, termLines.length]);

  // resize handle
  const containerRef = React.useRef(null);
  const dragging = React.useRef(false);
  const onDragStart = (e) => {
    dragging.current = true;
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
  };
  React.useEffect(() => {
    const move = (e) => {
      if (!dragging.current || !containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      const w = ((e.clientX - rect.left) / rect.width) * 100;
      setLeftWidth(Math.min(60, Math.max(18, w)));
    };
    const up = () => {
      dragging.current = false;
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    };
    window.addEventListener('mousemove', move);
    window.addEventListener('mouseup', up);
    return () => {
      window.removeEventListener('mousemove', move);
      window.removeEventListener('mouseup', up);
    };
  }, [setLeftWidth]);

  return (
    <div ref={containerRef} className="page-fade-enter" style={{
      display: 'flex', height: '100%', background: 'var(--bg-canvas)',
      position: 'relative',
    }}>
      {/* LEFT: Avatar */}
      <div style={{
        width: `${leftWidth}%`, position: 'relative', minWidth: 0,
        flexShrink: 0,
      }}>
        <AvatarPresence state={aiState}/>
        {/* status badge */}
        <div style={{ position: 'absolute', top: 16, left: 16 }}>
          <StatusBadge state={aiState}/>
        </div>
        {/* Nexus name top right */}
        <div style={{ position: 'absolute', top: 14, right: 16,
          display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 2 }}>
          <div style={{ fontSize: 12, fontWeight: 500 }}>Aiden</div>
          <div style={{ fontSize: 10.5, color: 'var(--text-tertiary)',
            fontFamily: 'JetBrains Mono', letterSpacing: '0.04em' }}>
            phoenix-4 · 32ms
          </div>
        </div>

        {/* Active subtitle when speaking */}
        {aiState === 'speaking' && (
          <div style={{
            position: 'absolute', left: 24, right: 24, bottom: 100,
            textAlign: 'center', color: 'rgba(255,255,255,0.85)',
            fontSize: 14, lineHeight: 1.5, fontWeight: 400,
            textShadow: '0 2px 12px rgba(0,0,0,0.6)',
            maxWidth: 460, margin: '0 auto',
          }}>
            "I'll wire up the optimistic insert next so adds feel instant — give me ten seconds."
          </div>
        )}
        {aiState === 'thinking' && (
          <div style={{
            position: 'absolute', left: '50%', bottom: 100, transform: 'translateX(-50%)',
            color: 'var(--accent-purple)', fontFamily: 'JetBrains Mono',
            fontSize: 12, letterSpacing: '0.08em',
            display: 'inline-flex', gap: 8, alignItems: 'center',
          }}>
            <span>thinking</span>
            <span style={{ animation: 'blink 1s steps(1) infinite' }}>...</span>
          </div>
        )}

        {/* controls */}
        <div style={{
          position: 'absolute', bottom: 28, left: '50%',
          transform: 'translateX(-50%)',
        }}>
          <AvatarControls
            muted={muted}
            onToggleMute={() => setMuted(m => !m)}
            onEnd={onLeave}
            state={aiState}
          />
        </div>
      </div>

      {/* RESIZE HANDLE */}
      <div onMouseDown={onDragStart} style={{
        width: 1, background: 'var(--border-subtle)',
        cursor: 'col-resize', position: 'relative', flexShrink: 0,
      }}>
        <div style={{
          position: 'absolute', left: -3, top: 0, bottom: 0,
          width: 7, cursor: 'col-resize',
        }}/>
        <div style={{
          position: 'absolute', left: -2, top: '50%',
          transform: 'translateY(-50%)',
          width: 5, height: 36, borderRadius: 999,
          background: 'var(--border-strong)',
          opacity: 0.6,
        }}/>
      </div>

      {/* RIGHT */}
      <div style={{
        flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column',
        background: 'var(--bg-surface)',
      }}>
        {/* Top nav */}
        <div className="glass" style={{
          height: 'var(--nav-h)',
          display: 'flex', alignItems: 'center',
          padding: '0 8px 0 0', flexShrink: 0,
          borderTop: 'none', borderRight: 'none', borderLeft: 'none',
        }}>
          <div className="tabbar" style={{ height: '100%' }}>
            <div onClick={() => setActiveTab('preview')}
              className={`tab ${activeTab === 'preview' ? 'active' : ''}`}>
              <span className="tab-icon">▶</span>Live Preview
            </div>
            <div onClick={() => setActiveTab('code')}
              className={`tab ${activeTab === 'code' ? 'active' : ''}`}>
              <IconCode size={13}/> Code
              {isStreaming && (
                <span className="status-dot speaking" style={{ width: 5, height: 5, marginLeft: 2 }}/>
              )}
            </div>
            <div onClick={() => setActiveTab('insights')}
              className={`tab ${activeTab === 'insights' ? 'active' : ''}`}>
              <IconBulb size={13}/> Insights
            </div>
          </div>
          <div style={{ flex: 1 }}/>

          {/* session timer */}
          <div className="mono" style={{
            display: 'flex', alignItems: 'center', gap: 8,
            padding: '0 14px', fontSize: 11.5,
            color: 'var(--text-tertiary)',
            borderRight: '1px solid var(--border-subtle)',
            height: 24,
          }}>
            <span className="status-dot speaking" style={{ width: 5, height: 5 }}/>
            <span>00:14:32</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '0 8px' }}>
            <button className="btn-icon" title="Export Code (.zip)">
              <IconDownload size={14}/>
            </button>
            <button className="btn-icon" title="Settings">
              <IconCog size={14}/>
            </button>
            <UserAvatar initials="AK" size={32} ring onClick={onNavProfile}/>
          </div>
        </div>

        {/* Tab content */}
        <div style={{ flex: 1, minHeight: 0, position: 'relative' }}>
          {activeTab === 'preview' && <LivePreview />}
          {activeTab === 'code' && (
            <CodeEditor streamProgress={streamProgress} isStreaming={isStreaming}/>
          )}
          {activeTab === 'insights' && (
            <InsightsTab termLines={termLines} isStreaming={isStreaming}/>
          )}
        </div>
      </div>
    </div>
  );
};

window.Workspace = Workspace;
